### ISSUE TITLE
Allow running Drupal FunctionalJavascript tests

### ISSUE THREAD

**Issue by eojthebrave** [Lullabot/drainpipe-dev#44]
I might be missing something, so please point me in the right direction if I am. But, I wanted to run some FunctionalJavascript tests in a Drupal contrib module using the selenium containers provided by this project. And in order to do so I added the following to the .ddev/docker-compose.selenium.yaml file:

```yaml
services:

  web:
    environment:
      - SIMPLETEST_DB=mysql://db:db@ddev-${DDEV_SITENAME}-db:3306/db
      - SIMPLETEST_BASE_URL=${DDEV_PRIMARY_URL}
      - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
      - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_PRIMARY_URL}
      - MINK_DRIVER_ARGS_WEBDRIVER=["chrome", {"browserName":"chrome","chromeOptions":{"args":["--ignore-certificate-errors","--no-sandbox","--allow-insecure-localhost","--disable-dev-shm-usage"]}}, "http://chrome:4444/wd/hub"]
```

This adds some configuration for phpunit to connect to Chrome/Selenium instances.

And then I can run these tests like:

```shell
ddev exec ./vendor/bin/phpunit --verbose -c web/core/ web/modules/contrib/user_guide_tests/tests/src/FunctionalJavascript/
```

I'm happy to create a PR if this seems like a useful addition. But wanted to see if y'all thought this was the correct approach first.
